<script language="javascript" type="text/javascript">
document.write("<style type='text/css'>");
document.write("        table {");
document.write("            display: block; ");
document.write("        }");
document.write("        tr {");
document.write("            align: left")
document.write("            width: 100%");
document.write("        }");
document.write("        td {");
document.write("            display: inline-block;");
document.write("        }"); 
document.write("        figure {");
document.write("            float: right;");
document.write("            width: 100%;");            
document.write("            text-align: center;"); 
document.write("            vertical-align: top");   
document.write("            border: thin silver solid;");   
document.write("            margin: 4px 4px 10px 4px "); 
document.write("        }");
document.write("        figcaption {");
document.write("            font-style: italic;");
document.write("            font-size: smaller;");
document.write("            text-decoration: underline; "); 
document.write("        }");
document.write("        figure > img {");
document.write("            width: 125px;");
document.write("            height: 100px;"); 
document.write("        }");
document.write("</style>");
document.write("</script>");
